name: deepec
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - diamond>=0.9.25
  - absl-py=0.12.0
  - pip=19.0.3
  - libprotobuf=3.15.8
  - protobuf=3.15.8
  - tensorflow=1.5.0
  - pip:
    - numpy==1.16.2
    - biopython==1.70
    - h5py==2.7.1
    - importlib-resources==5.4.0
    - keras==2.1.6
    - markdown==2.6.11
    - mock==2.0.0
    - pandas==0.19.2
    - scikit-learn
    - scipy==1.1.0
    - sklearn==0.0    
