name: deepec
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - diamond=0.9.24
  - pip=19.0.3
  - pip:
    - numpy==1.16.2
    - absl-py==0.4.1
    - backports.weakref==1.0.post1
    - biopython==1.70
    - bleach==1.5.0
    - enum34==1.1.6
    - funcsigs==1.0.2
    - h5py==2.7.1
    - html5lib==0.9999999
    - keras==2.1.6
    - markdown==2.6.11
    - mock==2.0.0
    - pandas==0.19.2
    - pbr==4.2.0
    - protobuf==3.6.1
    - python-dateutil==2.7.3
    - pytz==2018.5
    - pyyaml==3.13
    - scikit-learn==0.19.0
    - scipy==1.1.0
    - six==1.11.0
    - sklearn==0.0
    - tensorflow==1.5.0
    - tensorflow-tensorboard==1.5.1
    - werkzeug==0.14.1
